version: "3.8"
services:
  web:
    build: .
    ports:
      - "4567:4567"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
    depends_on:
      - mongo
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
